import type { AssetType, AssetField } from "@workspace/api-zod";

const purchasePriceField: AssetField = {
  key: "purchasePrice",
  label: "Original purchase price",
  type: "number",
  required: false,
  help: "We will assume this is in your local currency.",
};

export const ASSET_TYPES: AssetType[] = [
  // ============ Watches & Jewelry ============
  {
    id: "luxury-watch",
    name: "Luxury Watch",
    category: "Watches & Jewelry",
    tagline: "Rolex, Patek, AP, Omega and other collectible timepieces",
    exampleAttributes: "Reference, box, papers, bracelet links, dial originality, polish history",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Rolex", help: "Manufacturer name as most buyers spell it." },
      { key: "model", label: "Model or reference", type: "text", required: true, placeholder: "Submariner 116610LN", help: "Model name and reference number if you know them." },
      { key: "year", label: "Year", type: "number", required: false, help: "Approximate year of the watch if known, not your purchase year." },
      purchasePriceField,
      { key: "boxAndPapers", label: "Box and papers", type: "select", required: false, options: ["Full set (box + papers + tags)", "Watch + box only", "Watch + papers only", "Watch only"] },
      { key: "lastService", label: "Last service year", type: "number", required: false, placeholder: "2024", help: "Year of last service if you have a receipt or sticker." },
      { key: "ownerCount", label: "Number of previous owners", type: "number", required: false },
      {
        key: "braceletLinksCount",
        label: "Bracelet links (approx.)",
        type: "text",
        required: false,
        placeholder: "e.g., 12 links, full set",
      },
      {
        key: "dialBraceletOriginal",
        label: "Dial and bracelet originality",
        type: "select",
        required: false,
        options: ["Believed all original", "Service dial or hands", "Aftermarket bracelet or parts", "Unsure"],
      },
      {
        key: "polishHistory",
        label: "Case polish and wear",
        type: "select",
        required: false,
        options: ["Light wear, minimal polish", "Heavy polish or desk marks", "Sharp, likely unpolished", "Unsure"],
      },
    ],
  },
  {
    id: "fine-jewelry",
    name: "Fine Jewelry",
    category: "Watches & Jewelry",
    tagline: "Diamonds, rare stones, signed pieces",
    exampleAttributes: "Metal, carat summary, cert, size, maker",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand / Designer", type: "text", required: false, placeholder: "Cartier" },
      { key: "model", label: "Piece", type: "text", required: true, placeholder: "Love Bracelet, yellow gold" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      {
        key: "totalCarats",
        label: "Approx. total gem carats",
        type: "text",
        required: false,
        placeholder: "~1.2 ct center diamond",
        help: "Rough total carats for centerpiece stones helps calibrate comps when certificates are fuzzy.",
      },
      {
        key: "metal",
        label: "Metal",
        type: "select",
        required: false,
        options: ["18k yellow gold", "18k white gold", "18k rose gold", "Platinum", "Sterling silver", "Other"],
        help: "Hallmarks corroborate fineness stamps on European pieces.",
      },
      {
        key: "hallmark",
        label: "Hallmark / assay notes",
        type: "text",
        required: false,
        placeholder: 'e.g., "925" sterling, leopard head hallmark, assay office marks',
      },
      {
        key: "gemstones",
        label: "Main gemstones",
        type: "text",
        required: false,
        placeholder: "1.06 ct brilliant diamond + tapered baguettes vs GIA sapphire",
      },
      {
        key: "ringSizeOrLength",
        label: "Ring size / wearable length",
        type: "text",
        required: false,
        placeholder: 'Size 6.75 US · 17 cm bracelet circumference',
      },
      { key: "certificate", label: "Certificate", type: "select", required: false, options: ["GIA", "IGI", "AGS", "HRD", "None"] },
      {
        key: "diamondOrStoneSummary",
        label: "Main stone grades (if known)",
        type: "text",
        required: false,
        placeholder: "~1 ct G VS1 excellent cut GIA",
        help: "Short 4Cs or gem note so comps match certified vs uncertified markets.",
      },
    ],
  },
  {
    id: "vintage-watch",
    name: "Vintage Watch",
    category: "Watches & Jewelry",
    tagline: "Pre-1990s mechanical watches, military issued, and neo-vintage grails",
    exampleAttributes: "Movement, dial and hands, case polish, box and papers",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Omega" },
      { key: "model", label: "Model / Reference", type: "text", required: true, placeholder: "Speedmaster Pre-Moon 145.022" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "movement", label: "Movement", type: "text", required: false, placeholder: "Cal. 861" },
      { key: "boxAndPapers", label: "Box & papers?", type: "select", required: false, options: ["Full set", "Partial", "Watch only"] },
      {
        key: "dialHandsCondition",
        label: "Dial and hands condition",
        type: "select",
        required: false,
        options: ["Original patina, clean", "Relumed or replaced hands", "Refinished dial", "Unsure"],
      },
      {
        key: "casePolishLevel",
        label: "Case bevels / polish",
        type: "select",
        required: false,
        options: ["Strong bevels, light polish", "Soft edges, polished often", "Nicks and honest wear", "Unsure"],
      },
    ],
  },
  {
    id: "pocket-watch",
    name: "Pocket Watch",
    category: "Watches & Jewelry",
    tagline: "Antique and vintage open-face & hunter-case timepieces",
    exampleAttributes: "Case metal, complications, chain, running",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Maker", type: "text", required: false, placeholder: "Patek Philippe" },
      { key: "model", label: "Description", type: "text", required: true, placeholder: "Gondolo 18k hunter-case minute repeater" },
      { key: "year", label: "Circa year", type: "number", required: false },
      purchasePriceField,
      { key: "caseMaterial", label: "Case material", type: "select", required: false, options: ["Yellow gold", "Rose gold", "White gold", "Silver", "Steel", "Other"] },
      { key: "complications", label: "Complications", type: "text", required: false, placeholder: "Repeater, chronograph" },
      {
        key: "chainIncluded",
        label: "Original chain included?",
        type: "select",
        required: false,
        options: ["Yes, matching period chain", "Aftermarket chain", "No chain"],
      },
      {
        key: "runningCondition",
        label: "Running when wound?",
        type: "select",
        required: false,
        options: ["Runs and keeps time", "Runs, needs service", "Not running / parts", "Unsure"],
      },
    ],
  },

  // ============ Bags & Fashion ============
  {
    id: "designer-handbag",
    name: "Designer Handbag",
    category: "Bags & Fashion",
    tagline: "Hermès, Chanel, Louis Vuitton and other resale-grade bags",
    exampleAttributes: "Model size, color, leather, hardware, stamp, authenticity",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Hermès" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Birkin 30" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      {
        key: "authenticity",
        label: "Authenticity certainty",
        type: "select",
        required: false,
        options: ["Store / boutique purchase", "Consignment authenticity card", "Entrupy / third-party certification", "No paperwork · honest unknown"],
        help: "Higher certainty supports stronger resale comps; honesty keeps us from overstating liquidity.",
      },
      {
        key: "serialOrDateCode",
        label: "Serial / date code",
        type: "text",
        required: false,
        placeholder: "Stamped blind stamp, heat stamp…",
        help: "Hermès stamps, Chanel cards, LV date codes. Helps age the piece for buyers.",
      },
      {
        key: "authenticityServiceUrl",
        label: "Third-party authenticity link",
        type: "text",
        required: false,
        placeholder: "https://authenticatefirst.com/report/…",
        help: "Paste a shareable verifier URL when you already paid for certification.",
      },
      { key: "material", label: "Material / leather", type: "text", required: false, placeholder: "Togo leather" },
      { key: "color", label: "Color", type: "text", required: false, placeholder: "Etoupe" },
      { key: "hardware", label: "Hardware", type: "select", required: false, options: ["Gold", "Silver/Palladium", "Ruthenium", "Other"] },
      { key: "receiptIncluded", label: "Receipt included?", type: "select", required: false, options: ["Yes", "No"] },
      {
        key: "bagSizeLengthMm",
        label: "Size / length (mm or common name)",
        type: "text",
        required: false,
        placeholder: "Birkin 30 / 25cm / GM",
        help: "Many brands use length in cm or mm; include common name if known.",
      },
    ],
  },
  {
    id: "sneakers",
    name: "Collectible Sneakers",
    category: "Bags & Fashion",
    tagline: "Jordans, Yeezys, Dunks and resale grails",
    exampleAttributes: "Size, deadstock, OG box",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Nike" },
      { key: "model", label: "Model / Colorway", type: "text", required: true, placeholder: "Air Jordan 1 'Chicago Lost & Found'" },
      { key: "year", label: "Release year", type: "number", required: false },
      purchasePriceField,
      { key: "size", label: "Size (US men's)", type: "text", required: true, placeholder: "10" },
      { key: "ogBox", label: "OG box?", type: "select", required: false, options: ["Yes, perfect", "Yes, damaged", "No"] },
      {
        key: "wearSummary",
        label: "Quick wear check (optional)",
        type: "select",
        required: false,
        options: [
          "Like new / deadstock",
          "Light sole yellowing only",
          "Heavy sole yellowing or creasing",
          "Box damaged or missing extra laces",
        ],
      },
    ],
  },
  {
    id: "streetwear-apparel",
    name: "Streetwear & Apparel",
    category: "Bags & Fashion",
    tagline: "Supreme, Off-White, vintage band tees, hype drops",
    exampleAttributes: "Size, season, authenticity, print and fabric wear",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Supreme" },
      { key: "model", label: "Piece / drop", type: "text", required: true, placeholder: "Box Logo Hoodie FW17" },
      { key: "year", label: "Season / year", type: "number", required: false },
      purchasePriceField,
      { key: "size", label: "Size", type: "text", required: true, placeholder: "M" },
      { key: "authenticity", label: "Proof of authenticity", type: "select", required: false, options: ["Receipt / email order", "StockX / platform auth", "LOA", "No paperwork"] },
      {
        key: "apparelWearSummary",
        label: "Wear and flaws (visible)",
        type: "select",
        required: false,
        options: ["Like new, stored flat", "Light fade or pilling", "Print cracking or shrink", "Stains, holes, or heavy fade"],
      },
    ],
  },
  {
    id: "designer-accessories",
    name: "Designer Accessories",
    category: "Bags & Fashion",
    tagline: "Belts, scarves, small leather goods, sunglasses",
    exampleAttributes: "SKU or stamp, hardware, dust bag, box, corner wear",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Louis Vuitton" },
      { key: "model", label: "Item", type: "text", required: true, placeholder: "Monogram 40mm reversible belt" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "size", label: "Size / dimensions", type: "text", required: false },
      {
        key: "hardwareFinish",
        label: "Hardware color / finish",
        type: "text",
        required: false,
        placeholder: "Gold, palladium, gunmetal",
      },
      {
        key: "serialOrSku",
        label: "Serial, SKU, or heat stamp",
        type: "text",
        required: false,
        placeholder: "Inner stamp or tag number",
      },
      {
        key: "includesBoxDustBag",
        label: "Box and dust bag",
        type: "select",
        required: false,
        options: ["Full set (box + dust bag)", "Dust bag only", "Box only", "Neither"],
      },
      {
        key: "accessoryWearLevel",
        label: "Wear on canvas or leather",
        type: "select",
        required: false,
        options: ["Minimal", "Light corner rub", "Visible wear or stains", "Heavy use"],
      },
    ],
  },

  // ============ Vehicles ============
  {
    id: "classic-car",
    name: "Classic / Collector Car",
    category: "Vehicles",
    tagline: "Vintage, exotic and collectible cars",
    exampleAttributes: "Mileage, matching numbers, restoration, service",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Porsche" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "911 Carrera 3.2" },
      { key: "year", label: "Year", type: "number", required: true, placeholder: "1987" },
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: false, placeholder: "62000" },
      { key: "ownerCount", label: "Number of previous owners", type: "number", required: false, placeholder: "2" },
      { key: "matchingNumbers", label: "Matching numbers", type: "select", required: false, options: ["Yes, fully matching", "Engine replaced", "Unsure"], help: "Factory-correct engine and chassis stamps for the same car." },
      { key: "serviceHistory", label: "Service history", type: "select", required: false, options: ["Full main-dealer", "Full independent specialist", "Partial", "None"] },
      { key: "fuelType", label: "Fuel type", type: "select", required: false, options: ["Petrol", "Diesel", "Hybrid", "Electric"] },
      {
        key: "restorationExtent",
        label: "Restoration or refinish",
        type: "select",
        required: false,
        options: ["Original or unrestored", "Cosmetic refresh", "Full mechanical resto", "Unknown"],
      },
    ],
  },
  {
    id: "everyday-car",
    name: "Everyday Car",
    category: "Vehicles",
    tagline: "Daily-driver cars sold in the local market",
    exampleAttributes: "Mileage, trim, damage, MOT or inspection, keys, service",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Toyota" },
      { key: "model", label: "Model + trim", type: "text", required: true, placeholder: "Corolla Hybrid Excel" },
      { key: "year", label: "Year", type: "number", required: true },
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: true, placeholder: "48000" },
      { key: "ownerCount", label: "Previous owners", type: "number", required: false, placeholder: "2" },
      { key: "fuelType", label: "Fuel type", type: "select", required: true, options: ["Petrol", "Diesel", "Hybrid", "Plug-in Hybrid", "Electric"] },
      { key: "transmission", label: "Transmission", type: "select", required: false, options: ["Manual", "Automatic", "Other"] },
      { key: "serviceHistory", label: "Service history", type: "select", required: false, options: ["Full main-dealer", "Full independent", "Partial", "None"] },
      { key: "accidents", label: "Accidents or write-off history", type: "select", required: false, options: ["None", "Minor cosmetic", "Major repaired", "Cat S/N or write-off"], help: "UK Cat S/N means insurer wrote off the car; it stays on the record." },
      {
        key: "motOrInspectionNote",
        label: "MOT / inspection / registration note",
        type: "text",
        required: false,
        placeholder: "MOT to Nov 2026, 2 advisories",
      },
      {
        key: "spareKeys",
        label: "Keys included",
        type: "select",
        required: false,
        options: ["Two full keys", "One key only", "Key missing / spare unknown"],
      },
    ],
  },
  {
    id: "motorcycle",
    name: "Motorcycle",
    category: "Vehicles",
    tagline: "Modern and classic bikes",
    exampleAttributes: "Mileage, mods, title, drops, ABS",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Ducati" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Panigale V4" },
      { key: "year", label: "Year", type: "number", required: true },
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: true },
      { key: "ownerCount", label: "Previous owners", type: "number", required: false },
      { key: "mods", label: "Modifications", type: "text", required: false, placeholder: "Akrapovic exhaust, ECU flash" },
      {
        key: "titleStatus",
        label: "Title status",
        type: "select",
        required: false,
        options: ["Clean", "Salvage / rebuilt", "Other branded title", "Unsure / not declared"],
      },
      {
        key: "dropHistory",
        label: "Drop or crash history",
        type: "select",
        required: false,
        options: ["No drops declared", "Minor tip-over", "Major repair from crash", "Unsure"],
      },
      {
        key: "absEquipped",
        label: "ABS or advanced brakes",
        type: "select",
        required: false,
        options: ["Yes", "No", "Unsure"],
      },
    ],
  },
  {
    id: "boat-marine",
    name: "Boat / Marine",
    category: "Vehicles",
    tagline: "Powerboats, sailboats, RIBs, personal watercraft",
    exampleAttributes: "Length, hours, hull, survey, salt or fresh water",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make / Builder", type: "text", required: true, placeholder: "Sea Ray" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Sundancer 320" },
      { key: "year", label: "Year", type: "number", required: true },
      purchasePriceField,
      { key: "lengthFt", label: "Length (feet)", type: "number", required: false },
      { key: "engineHours", label: "Engine hours", type: "number", required: false },
      { key: "berth", label: "Home port / mooring", type: "text", required: false, placeholder: "Marina name" },
      {
        key: "hullMaterial",
        label: "Hull material",
        type: "select",
        required: false,
        options: ["Fiberglass", "Aluminium", "Wood", "Steel", "Inflatable / RIB", "Other"],
      },
      {
        key: "saltOrFreshwater",
        label: "Primary use water",
        type: "select",
        required: false,
        options: ["Freshwater", "Saltwater", "Mixed / trailer only"],
      },
      {
        key: "surveyWithinTwoYears",
        label: "Survey within last 2 years?",
        type: "select",
        required: false,
        options: ["Yes, clean survey", "Yes, with findings", "No survey", "Unsure"],
      },
    ],
  },
  {
    id: "rv-camper",
    name: "RV / Camper",
    category: "Vehicles",
    tagline: "Motorhomes, camper vans, travel trailers",
    exampleAttributes: "Miles, sleeps, slides, water damage, generator",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Winnebago" },
      { key: "model", label: "Model + floorplan", type: "text", required: true, placeholder: "Revel 4x4" },
      { key: "year", label: "Year", type: "number", required: true },
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: false },
      { key: "sleeps", label: "Sleeps (people)", type: "number", required: false },
      { key: "generator", label: "Generator / solar", type: "text", required: false },
      {
        key: "slideOuts",
        label: "Slide-outs",
        type: "select",
        required: false,
        options: ["None", "One slide", "Multiple slides", "Unsure"],
      },
      {
        key: "waterDamageKnown",
        label: "Known water or delamination damage?",
        type: "select",
        required: false,
        options: ["None known", "Repaired historically", "Active leak or soft floor", "Unsure"],
      },
    ],
  },

  // ============ Electronics ============
  {
    id: "smartphone",
    name: "Smartphone",
    category: "Electronics",
    tagline: "iPhones, Pixels, Galaxies, current and older models",
    exampleAttributes: "Storage, lock, battery, box, screen and body wear",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Apple" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "iPhone 15 Pro Max" },
      { key: "year", label: "Year of purchase", type: "number", required: false },
      purchasePriceField,
      { key: "storage", label: "Storage", type: "select", required: false, options: ["64GB", "128GB", "256GB", "512GB", "1TB", "2TB"] },
      { key: "color", label: "Color", type: "text", required: false },
      { key: "networkLock", label: "Network status", type: "select", required: false, options: ["Unlocked", "Carrier-locked"] },
      { key: "batteryHealth", label: "Battery health %", type: "number", required: false, placeholder: "92" },
      { key: "boxAndAccessories", label: "Box / accessories", type: "select", required: false, options: ["Original box + cable + all accessories", "Box only", "None"] },
      {
        key: "screenWear",
        label: "Screen condition (optional)",
        type: "select",
        required: false,
        options: ["No visible wear", "Light scratches", "Heavy scratches", "Cracked or chipped"],
      },
      {
        key: "bodyWear",
        label: "Body / frame (optional)",
        type: "select",
        required: false,
        options: ["No dents or scuffs", "Minor scuffs", "Visible dents or cracks"],
      },
      {
        key: "warrantyRemaining",
        label: "Warranty or AppleCare left?",
        type: "select",
        required: false,
        options: ["Yes, active", "Expired", "Unsure"],
      },
    ],
  },
  {
    id: "laptop",
    name: "Laptop / Computer",
    category: "Electronics",
    tagline: "MacBooks, gaming laptops, desktops",
    exampleAttributes: "CPU, RAM, storage, GPU, screen size, warranty",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Apple" },
      { key: "model", label: "Model + spec", type: "text", required: true, placeholder: "MacBook Pro 14 M3 Pro 18GB/512GB" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "cpu", label: "CPU", type: "text", required: false },
      { key: "ram", label: "RAM (GB)", type: "number", required: false },
      { key: "storage", label: "Storage (GB)", type: "number", required: false },
      { key: "gpu", label: "GPU (if applicable)", type: "text", required: false },
      { key: "batteryHealth", label: "Battery cycles / health", type: "text", required: false },
      {
        key: "screenSizeInch",
        label: "Screen size (inches)",
        type: "text",
        required: false,
        placeholder: "14",
      },
      {
        key: "warrantyRemaining",
        label: "Warranty remaining?",
        type: "select",
        required: false,
        options: ["Yes, active", "Expired", "Unsure"],
      },
    ],
  },
  {
    id: "gaming-console",
    name: "Gaming Console",
    category: "Electronics",
    tagline: "PS5, Xbox, Switch and retro consoles",
    exampleAttributes: "Disc or digital, storage, controllers, box",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Sony" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "PlayStation 5 Slim" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "storage", label: "Storage", type: "text", required: false, placeholder: "1TB" },
      { key: "controllers", label: "Controllers included", type: "number", required: false },
      { key: "boxAndAccessories", label: "Box / accessories", type: "select", required: false, options: ["Original box + all cables", "Cables only", "Bare console"] },
      {
        key: "discOrDigital",
        label: "Disc drive or all-digital model",
        type: "select",
        required: false,
        options: ["Disc drive", "All-digital / no disc", "N/A or unsure"],
      },
    ],
  },
  {
    id: "camera",
    name: "Camera & Lenses",
    category: "Electronics",
    tagline: "Mirrorless, DSLR, film cameras and pro glass",
    exampleAttributes: "Shutter count, sensor format, lenses bundled",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Sony" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "A7 IV body" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "shutterCount", label: "Shutter actuations", type: "number", required: false },
      { key: "lenses", label: "Lenses included", type: "text", required: false, placeholder: "24-70 f/2.8 GM, 70-200 f/4 G" },
      {
        key: "sensorFormat",
        label: "Sensor format",
        type: "select",
        required: false,
        options: ["Full frame", "APS-C", "Micro Four Thirds", "Medium format", "Film / other", "Unsure"],
      },
    ],
  },
  {
    id: "tablet",
    name: "Tablet",
    category: "Electronics",
    tagline: "iPad, Galaxy Tab, Surface, e-readers",
    exampleAttributes: "Storage, cellular, screen size, accessories",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Apple" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "iPad Pro 12.9 M2" },
      { key: "year", label: "Year of purchase", type: "number", required: false },
      purchasePriceField,
      { key: "storage", label: "Storage", type: "text", required: false, placeholder: "256GB" },
      { key: "cellular", label: "Cellular?", type: "select", required: false, options: ["WiFi only", "WiFi + Cellular", "N/A"] },
      { key: "boxAndAccessories", label: "Box / accessories", type: "select", required: false, options: ["Original box + charger + pen/keyboard", "Charger only", "Device only"] },
      {
        key: "screenSizeInch",
        label: "Screen size (inches)",
        type: "text",
        required: false,
        placeholder: "11 or 12.9",
      },
      {
        key: "warrantyRemaining",
        label: "Warranty remaining?",
        type: "select",
        required: false,
        options: ["Yes, active", "Expired", "Unsure"],
      },
    ],
  },
  {
    id: "audio-hifi",
    name: "Hi-Fi / Audio",
    category: "Electronics",
    tagline: "Headphones, earbuds, portable DACs, plus speakers and hi-fi gear",
    exampleAttributes: "Form factor, finish, tube or solid state, packaging",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Focal" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Utopia 2022" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "formFactor", label: "Form factor", type: "select", required: false, options: ["Over-ear", "On-ear", "Earbuds / IEM", "Portable DAC / amp", "Speaker or other"] },
      { key: "finish", label: "Finish / color", type: "text", required: false },
      { key: "originalBox", label: "Original packaging?", type: "select", required: false, options: ["Full retail box", "Partial", "None"] },
      {
        key: "amplifierTopology",
        label: "Amplifier type (if applicable)",
        type: "select",
        required: false,
        options: ["N/A (headphones, DAC, etc.)", "Tube", "Solid state", "Hybrid", "Unsure"],
      },
    ],
  },
  {
    id: "drone-uav",
    name: "Drone / UAV",
    category: "Electronics",
    tagline: "Camera drones, FPV, enterprise UAVs",
    exampleAttributes: "Flight hours, crashes, gimbal, Care plan, batteries",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "DJI" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Mavic 3 Pro" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "flightHours", label: "Approx. flight hours", type: "number", required: false },
      { key: "batteries", label: "Batteries included", type: "number", required: false },
      { key: "registration", label: "FAA / local registration status", type: "text", required: false },
      {
        key: "crashHistory",
        label: "Crash or hard landing history",
        type: "select",
        required: false,
        options: ["None declared", "Minor tip, repaired", "Major crash or gimbal replaced", "Unsure"],
      },
      {
        key: "gimbalCondition",
        label: "Gimbal and camera",
        type: "select",
        required: false,
        options: ["Clean, no rub", "Minor wear", "Issues / replacement", "Unsure"],
      },
      {
        key: "careRefreshActive",
        label: "DJI Care or similar active?",
        type: "select",
        required: false,
        options: ["Yes", "Expired", "N/A or unsure"],
      },
    ],
  },

  // ============ Real Estate ============
  {
    id: "residential-property",
    name: "Residential Property",
    category: "Real Estate",
    tagline: "Houses, flats, condos (owned or being sold)",
    exampleAttributes: "Beds, bath, sq ft, tenure, lease years, EPC, chain",
    internationallyTradeable: false,
    fields: [
      { key: "model", label: "Property type", type: "select", required: true, options: ["Detached house", "Semi-detached", "Terraced", "Apartment / Flat", "Condo", "Townhouse", "Bungalow"] },
      { key: "brand", label: "Neighbourhood / area", type: "text", required: true, placeholder: "Hampstead, London NW3" },
      { key: "year", label: "Year built", type: "number", required: false },
      purchasePriceField,
      { key: "bedrooms", label: "Bedrooms", type: "number", required: true },
      { key: "bathrooms", label: "Bathrooms", type: "number", required: false },
      { key: "sqft", label: "Internal area (sq ft)", type: "number", required: false },
      { key: "outdoorSpace", label: "Outdoor space", type: "select", required: false, options: ["Garden", "Balcony", "Terrace", "None"] },
      { key: "tenure", label: "Tenure", type: "select", required: false, options: ["Freehold", "Leasehold", "Share of freehold", "N/A"] },
      {
        key: "chainStatus",
        label: "Sale chain status",
        type: "select",
        required: false,
        options: ["No chain", "Chain in progress", "Unsure"],
      },
      {
        key: "leaseYearsRemaining",
        label: "Lease years left (if leasehold)",
        type: "number",
        required: false,
        placeholder: "e.g., 87",
      },
      {
        key: "epcRating",
        label: "Energy rating (EPC or local equivalent)",
        type: "text",
        required: false,
        placeholder: "B / 72",
      },
      {
        key: "majorWorksRecent",
        label: "Major works (roof, windows, extension)",
        type: "text",
        required: false,
        placeholder: "New kitchen 2022, loft 2019",
      },
    ],
  },
  {
    id: "commercial-property",
    name: "Commercial Property",
    category: "Real Estate",
    tagline: "Retail units, offices, warehouses, mixed-use",
    exampleAttributes: "Sq ft, tenant, passing rent, yield, lease length",
    internationallyTradeable: false,
    fields: [
      { key: "model", label: "Property type", type: "select", required: true, options: ["Retail high street", "Shopping unit", "Office", "Industrial / warehouse", "Mixed-use", "Other"] },
      { key: "brand", label: "Location / city", type: "text", required: true, placeholder: "Manchester city centre" },
      { key: "year", label: "Year built", type: "number", required: false },
      purchasePriceField,
      { key: "sqft", label: "Internal / lettable area (sq ft)", type: "number", required: false },
      { key: "tenure", label: "Tenure", type: "select", required: false, options: ["Freehold", "Long leasehold", "Short leasehold"] },
      { key: "tenant", label: "Tenant / vacancy", type: "text", required: false, placeholder: "Vacant / 5 yr NNN lease to chain" },
      {
        key: "passingRentAnnual",
        label: "Passing rent (per year, local currency)",
        type: "text",
        required: false,
        placeholder: "24000",
      },
      {
        key: "yieldsPercentApprox",
        label: "Net yield % (if you know it)",
        type: "text",
        required: false,
        placeholder: "6.5",
      },
      {
        key: "leaseYearsRemaining",
        label: "Lease years remaining",
        type: "number",
        required: false,
      },
    ],
  },
  {
    id: "land-plot",
    name: "Land / Plot",
    category: "Real Estate",
    tagline: "Building plots, agricultural land, woodland",
    exampleAttributes: "Acres, planning, road access, utilities",
    internationallyTradeable: false,
    fields: [
      { key: "model", label: "Land type", type: "select", required: true, options: ["Building plot", "Agricultural", "Woodland", "Pasture", "Brownfield", "Other"] },
      { key: "brand", label: "Location", type: "text", required: true, placeholder: "Near Bath, SN13" },
      { key: "acreage", label: "Size (acres)", type: "number", required: false, help: "Use decimals for partial acres" },
      purchasePriceField,
      { key: "planning", label: "Planning status", type: "text", required: false, placeholder: "Outline PP for 4-bed dwelling" },
      {
        key: "roadAccess",
        label: "Vehicle access",
        type: "select",
        required: false,
        options: ["Direct from public road", "Via easement or track", "No vehicle access yet", "Unsure"],
      },
      {
        key: "utilitiesNearby",
        label: "Mains services nearby",
        type: "text",
        required: false,
        placeholder: "Water at boundary, no sewer",
      },
    ],
  },

  // ============ Collectibles & Art ============
  {
    id: "fine-art",
    name: "Fine Art",
    category: "Collectibles & Art",
    tagline: "Paintings, prints, sculpture",
    exampleAttributes: "Artist, medium, edition, framing, signature",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Artist", type: "text", required: true, placeholder: "KAWS" },
      { key: "model", label: "Title / Edition", type: "text", required: true, placeholder: "Companion (Open Edition)" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "medium", label: "Medium", type: "text", required: false, placeholder: "Screen print on Saunders paper" },
      { key: "edition", label: "Edition number / size", type: "text", required: false, placeholder: "23 / 100" },
      { key: "provenance", label: "Provenance", type: "text", required: false, placeholder: "Gagosian Gallery, COA included" },
      {
        key: "framed",
        label: "Framed?",
        type: "select",
        required: false,
        options: ["Yes, museum or quality frame", "Yes, basic frame", "Unframed", "Unsure"],
      },
      {
        key: "signedVisible",
        label: "Signature visible on work?",
        type: "select",
        required: false,
        options: ["Yes", "No / print only", "Unsure"],
      },
    ],
  },
  {
    id: "trading-cards",
    name: "Trading Cards",
    category: "Collectibles & Art",
    tagline: "Sports cards, Pokémon, Magic, etc.",
    exampleAttributes: "Grade, variant, serial or parallel",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Set / Game", type: "text", required: true, placeholder: "Pokémon Base Set" },
      { key: "model", label: "Card", type: "text", required: true, placeholder: "Charizard Holo 1st Edition" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "grade", label: "Grade & grader", type: "text", required: false, placeholder: "PSA 9" },
      { key: "edition", label: "Edition / set marker", type: "text", required: false, placeholder: "Shadowless 1st edition" },
      {
        key: "serialOrParallel",
        label: "Serial numbered or parallel?",
        type: "select",
        required: false,
        options: ["No", "Yes, /xx serial", "Parallel or SSP variant", "Unsure"],
      },
    ],
  },
  {
    id: "wine-spirits",
    name: "Wine & Spirits",
    category: "Collectibles & Art",
    tagline: "Investment-grade wine, whisky, rare bottles",
    exampleAttributes: "Vintage, fill level, storage, provenance",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Producer", type: "text", required: true, placeholder: "Macallan" },
      { key: "model", label: "Bottling", type: "text", required: true, placeholder: "25 Year Sherry Oak" },
      { key: "year", label: "Vintage / Release year", type: "number", required: false },
      purchasePriceField,
      { key: "bottleSize", label: "Bottle size", type: "select", required: false, options: ["375ml", "500ml", "700ml / 750ml", "1L", "1.5L Magnum", "3L Jeroboam", "Other"] },
      { key: "fillLevel", label: "Fill level", type: "select", required: false, options: ["Into neck / pristine", "High shoulder", "Mid shoulder", "Low shoulder", "Below"] },
      {
        key: "wineCellarStorage",
        label: "How it was stored",
        type: "select",
        required: false,
        help: "Cool, stable storage protects value more than bottles kept hot or in direct sun.",
        options: [
          "Professional bonded warehouse",
          "Climate-controlled cellar",
          "Domestic wine fridge",
          "Cool dark cupboard",
          "Room temperature shelf",
        ],
      },
      { key: "sealed", label: "Seal intact / unopened?", type: "select", required: false, options: ["Yes, sealed", "Capsule slightly worn", "Opened"] },
      { key: "originalBox", label: "Original box / tube?", type: "select", required: false, options: ["Yes, mint", "Yes, worn", "No"] },
    ],
  },
  {
    id: "vinyl-records",
    name: "Vinyl Records",
    category: "Collectibles & Art",
    tagline: "First pressings, rare LPs, signed copies",
    exampleAttributes: "Pressing, matrix, sleeve & vinyl grade",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Artist", type: "text", required: true, placeholder: "The Beatles" },
      { key: "model", label: "Album / pressing", type: "text", required: true, placeholder: "Please Please Me, stereo UK 1st press" },
      { key: "year", label: "Pressing year", type: "number", required: false },
      purchasePriceField,
      { key: "vinylGrade", label: "Vinyl grade", type: "select", required: false, options: ["Mint (M)", "Near Mint (NM)", "Very Good Plus (VG+)", "Very Good (VG)", "Good (G)", "Fair (F)"] },
      { key: "sleeveGrade", label: "Sleeve grade", type: "select", required: false, options: ["Mint (M)", "Near Mint (NM)", "Very Good Plus (VG+)", "Very Good (VG)", "Good (G)", "Fair (F)"] },
      { key: "matrix", label: "Matrix / runout details", type: "text", required: false },
    ],
  },
  {
    id: "rare-books",
    name: "Rare Books",
    category: "Collectibles & Art",
    tagline: "First editions, signed copies, antiquarian",
    exampleAttributes: "Edition, dust jacket, foxing, signatures",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Author", type: "text", required: true, placeholder: "J.K. Rowling" },
      { key: "model", label: "Title + edition", type: "text", required: true, placeholder: "Harry Potter and the Philosopher's Stone (1st UK 1st print)" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "dustJacket", label: "Dust jacket", type: "select", required: false, options: ["Original, fine", "Original, worn", "Price-clipped", "Missing"] },
      { key: "signed", label: "Signed?", type: "select", required: false, options: ["Yes, in person with COA", "Yes, claimed", "No"] },
      {
        key: "foxingLevel",
        label: "Foxing or stains on pages",
        type: "select",
        required: false,
        options: ["None visible", "Light foxing", "Heavy foxing or stains", "Unsure"],
      },
    ],
  },
  {
    id: "musical-instrument",
    name: "Musical Instrument",
    category: "Collectibles & Art",
    tagline: "Guitars, pianos, vintage synths",
    exampleAttributes: "Maker, frets, neck, originality, case",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Maker", type: "text", required: true, placeholder: "Fender" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "American Vintage II '63 Tele" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "originality", label: "Originality", type: "select", required: false, options: ["All original", "Minor period-correct mods", "Modified"] },
      { key: "caseIncluded", label: "Case included?", type: "select", required: false, options: ["Original hard case", "Aftermarket case", "Soft case", "None"] },
      {
        key: "fretWearLevel",
        label: "Fret wear (guitars)",
        type: "select",
        required: false,
        options: ["N/A or light use", "Visible wear", "Needs refret", "Unsure"],
      },
      {
        key: "neckStraight",
        label: "Neck straight / playable?",
        type: "select",
        required: false,
        options: ["Yes", "Needs setup", "Known twist or repair", "Unsure"],
      },
    ],
  },

  // ============ Furniture & Antiques ============
  {
    id: "designer-furniture",
    name: "Designer Furniture",
    category: "Home & Antiques",
    tagline: "Eames, Knoll, Vitra, mid-century classics",
    exampleAttributes: "Maker, year, labels, dimensions, restoration",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Maker / Designer", type: "text", required: true, placeholder: "Herman Miller / Charles Eames" },
      { key: "model", label: "Piece", type: "text", required: true, placeholder: "Lounge Chair & Ottoman, rosewood" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "originality", label: "Originality", type: "select", required: false, options: ["All original", "Reupholstered (period-correct)", "Restored"] },
      {
        key: "dimensionsApproxCm",
        label: "Dimensions (W x D x H cm)",
        type: "text",
        required: false,
        placeholder: "84 x 84 x 85",
      },
      {
        key: "makerLabelPresent",
        label: "Maker label or stamp visible?",
        type: "select",
        required: false,
        options: ["Yes", "Partial / faded", "No", "Unsure"],
      },
    ],
  },
  {
    id: "antique",
    name: "Antique / Heirloom",
    category: "Home & Antiques",
    tagline: "100+ year-old pieces, family heirlooms",
    exampleAttributes: "Period, maker, provenance, restoration, woodworm",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Maker / Workshop", type: "text", required: false },
      { key: "model", label: "Piece", type: "text", required: true, placeholder: "Georgian mahogany sideboard" },
      { key: "year", label: "Approx. year / period", type: "number", required: false },
      purchasePriceField,
      { key: "provenance", label: "Provenance", type: "text", required: false },
      {
        key: "restorationExtentAntique",
        label: "Restoration or repairs",
        type: "select",
        required: false,
        options: ["None known", "Minor sympathetic repair", "Major structural restore", "Unsure"],
      },
      {
        key: "woodwormOrDamage",
        label: "Woodworm, cracks, or loose joints?",
        type: "select",
        required: false,
        options: ["None declared", "Treated historically", "Active issues", "Unsure"],
      },
    ],
  },
  {
    id: "premium-rug",
    name: "Rug / Textile Art",
    category: "Home & Antiques",
    tagline: "Persian, Oriental, designer rugs, tapestries",
    exampleAttributes: "Knot density, pile wear, size, materials, age",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Origin / workshop", type: "text", required: false, placeholder: "Tabriz" },
      { key: "model", label: "Style / pattern", type: "text", required: true, placeholder: "9x12 medallion, wool & silk" },
      { key: "year", label: "Approx. age (years)", type: "number", required: false },
      purchasePriceField,
      { key: "dimensions", label: "Dimensions (feet W x L)", type: "text", required: false, placeholder: "8.5 x 11.2" },
      { key: "material", label: "Materials", type: "text", required: false, placeholder: "Hand-knotted wool" },
      {
        key: "knotDensityApprox",
        label: "Knot density (approx. KPSI or quality tier)",
        type: "text",
        required: false,
        placeholder: "Fine weave / ~400+ KPSI",
      },
      {
        key: "pileWearLevel",
        label: "Pile wear and edges",
        type: "select",
        required: false,
        options: ["Even pile, secure edges", "Low areas or minor wear", "Visible wear, fringe loss", "Unsure"],
      },
    ],
  },

  // ============ Collectibles (memorabilia) ============
  {
    id: "sports-memorabilia",
    name: "Sports Memorabilia",
    category: "Collectibles & Art",
    tagline: "Signed shirts, match-worn kit, equipment",
    exampleAttributes: "Athlete, auth, match-worn, framing",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Sport / League", type: "text", required: true, placeholder: "NBA" },
      { key: "model", label: "Item + athlete", type: "text", required: true, placeholder: "Michael Jordan signed 1996 Bulls jersey" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "authentication", label: "Authentication", type: "select", required: false, options: ["JSA", "PSA/DNA", "Beckett", "Upper Deck", "Other COA", "None"] },
      { key: "matchWorn", label: "Match-worn / used?", type: "select", required: false, options: ["Match-worn (with photo match)", "Match-worn (claimed)", "Signed only / not used"] },
      {
        key: "displayOrFramed",
        label: "Framed or display-ready?",
        type: "select",
        required: false,
        options: ["Loose / folded", "Framed or shadowbox", "Case only"],
      },
    ],
  },
  {
    id: "comic-books",
    name: "Comic Books",
    category: "Collectibles & Art",
    tagline: "Golden Age to modern keys, manga, graphic novels",
    exampleAttributes: "Grade, variant, page quality, restoration",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Publisher / imprint", type: "text", required: true, placeholder: "Marvel" },
      { key: "model", label: "Title & issue", type: "text", required: true, placeholder: "Amazing Fantasy #15" },
      { key: "year", label: "Cover year", type: "number", required: false },
      purchasePriceField,
      { key: "grade", label: "Grade & grader", type: "text", required: false, placeholder: "CGC 4.0" },
      { key: "variant", label: "Variant cover / printing", type: "text", required: false },
      {
        key: "pageQuality",
        label: "Page quality (ungraded)",
        type: "select",
        required: false,
        options: ["Off-white to white", "Tanning or small defects", "Brittle or missing pieces", "Graded slab only"],
      },
      {
        key: "professionallyRestored",
        label: "Colour touch or restoration?",
        type: "select",
        required: false,
        options: ["None known", "Minor conservation", "Colour touch or rebuilt spine", "Unsure"],
      },
    ],
  },
  {
    id: "numismatics",
    name: "Coins & Currency",
    category: "Collectibles & Art",
    tagline: "Gold & silver bullion, graded coins, banknotes",
    exampleAttributes: "Country, grade, metal, key date or variety",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Country / mint", type: "text", required: true, placeholder: "Royal Mint" },
      { key: "model", label: "Denomination & year", type: "text", required: true, placeholder: "1933 Double Eagle (copy)" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "grade", label: "Grade & service", type: "text", required: false, placeholder: "MS-65 PCGS" },
      { key: "metal", label: "Metal / purity", type: "text", required: false, placeholder: ".999 silver 1 oz" },
      {
        key: "keyDateOrVariety",
        label: "Key date, error, or variety note",
        type: "text",
        required: false,
        placeholder: "1921 Morgan, VAM-12",
      },
    ],
  },
  {
    id: "philately",
    name: "Stamps",
    category: "Collectibles & Art",
    tagline: "Classic issues, sheets, postal history",
    exampleAttributes: "Catalogue ref, mint or hinged, certificate",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Country", type: "text", required: true, placeholder: "Great Britain" },
      { key: "model", label: "Issue / catalogue ref", type: "text", required: true, placeholder: "Penny Black (used, 4 margin)" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "catalogue", label: "Catalogue value note", type: "text", required: false, placeholder: "SG catalog £X mint" },
      { key: "certification", label: "Expert certificate?", type: "select", required: false, options: ["Yes", "No", "Pending"] },
      {
        key: "mintOrHinged",
        label: "Mint never hinged or used?",
        type: "select",
        required: false,
        options: ["MNH", "Mint hinged", "Used", "On piece or cover", "Unsure"],
      },
    ],
  },

  // ============ Sports & Outdoors ============
  {
    id: "bicycle",
    name: "Bicycle",
    category: "Sports & Outdoors",
    tagline: "Road, gravel, mountain, e-bikes",
    exampleAttributes: "Frame material, size, groupset, e-bike, mileage",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Specialized" },
      { key: "model", label: "Model + size", type: "text", required: true, placeholder: "S-Works Tarmac SL8, 56cm" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "groupset", label: "Groupset", type: "text", required: false, placeholder: "Shimano Dura-Ace Di2" },
      { key: "mileage", label: "Approx. mileage (km)", type: "number", required: false },
      { key: "ownerCount", label: "Previous owners", type: "number", required: false },
      {
        key: "frameMaterial",
        label: "Frame material",
        type: "select",
        required: false,
        options: ["Carbon", "Aluminium", "Steel", "Titanium", "Other", "Unsure"],
      },
      {
        key: "electricAssist",
        label: "E-bike / motor assist?",
        type: "select",
        required: false,
        options: ["No", "Yes, factory", "Yes, retrofit", "Unsure"],
      },
    ],
  },
  {
    id: "golf-equipment",
    name: "Golf Clubs & Gear",
    category: "Sports & Outdoors",
    tagline: "Drivers, irons, putters, bags, launch monitors",
    exampleAttributes: "Loft, flex, lie adjustment, what's included",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Titleist" },
      { key: "model", label: "Set / club", type: "text", required: true, placeholder: "TSR3 driver 9°, HZRDUS shaft" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "shaftFlex", label: "Shaft flex", type: "text", required: false, placeholder: "Stiff" },
      { key: "setMakeup", label: "What's included", type: "text", required: false, placeholder: "4-PW + gap wedge, cart bag" },
      {
        key: "driverLoftDegrees",
        label: "Driver loft (degrees, if selling a driver)",
        type: "text",
        required: false,
        placeholder: "10.5",
      },
      {
        key: "lieAdjusted",
        label: "Shafts bent / lie adjusted?",
        type: "select",
        required: false,
        options: ["Stock / standard", "Custom lie or length", "Unsure"],
      },
    ],
  },
  {
    id: "winter-sports",
    name: "Winter Sports Gear",
    category: "Sports & Outdoors",
    tagline: "Skis, snowboards, boots, bindings",
    exampleAttributes: "Length, boot mondo, edge and base condition",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Atomic" },
      { key: "model", label: "Model + size", type: "text", required: true, placeholder: "Bent Chetler 100, 180cm" },
      { key: "year", label: "Season / year", type: "number", required: false },
      purchasePriceField,
      { key: "bindings", label: "Bindings", type: "text", required: false, placeholder: "Shift 13 MN" },
      {
        key: "bootMondo",
        label: "Boot sole length (mondo, mm)",
        type: "text",
        required: false,
        placeholder: "270",
      },
      {
        key: "edgeBaseCondition",
        label: "Edges and bases",
        type: "select",
        required: false,
        options: ["Recently tuned", "Minor rust or scratches", "Core shots or big gouges", "Unsure"],
      },
    ],
  },
  {
    id: "camping-outdoor",
    name: "Camping & Hiking",
    category: "Sports & Outdoors",
    tagline: "Tents, backpacks, sleeping systems, cookware",
    exampleAttributes: "Season rating, packed weight, seams, poles",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Hilleberg" },
      { key: "model", label: "Item", type: "text", required: true, placeholder: "Keron 4 GT tent" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      {
        key: "seasonComfort",
        label: "Season rating",
        type: "select",
        required: false,
        help: "Rough warmth rating: summer-only gear vs year-round mountain use.",
        options: ["Summer / 1-season", "3-season", "4-season / expedition", "Unsure"],
      },
      {
        key: "seamOrPoleIssues",
        label: "Seams, zips, or poles",
        type: "select",
        required: false,
        options: ["All sound", "Minor tape or wear", "Tears, leaks, or bent poles", "Unsure"],
      },
      {
        key: "packedWeightKg",
        label: "Packed weight (kg)",
        type: "number",
        required: false,
        help: "Manufacturer spec or your kitchen scale, bag packed as for a trip.",
      },
    ],
  },
  {
    id: "fitness-equipment",
    name: "Home Fitness Equipment",
    category: "Sports & Outdoors",
    tagline: "Bikes, rowers, racks, adjustable dumbbells",
    exampleAttributes: "Usage hours, screen, subscription, accessories",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Peloton" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Bike+ with rotating screen" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      { key: "usage", label: "Approx. rides / hours", type: "text", required: false, placeholder: "450 rides" },
      { key: "subscription", label: "Subscription transferable?", type: "select", required: false, options: ["Yes", "No", "N/A"] },
      {
        key: "includesAccessories",
        label: "Heart-rate band, weights, or extras",
        type: "select",
        required: false,
        options: ["Full retail bundle", "Core machine only", "Mix of extras", "Unsure"],
      },
    ],
  },
  {
    id: "saas-micro",
    name: "SaaS / Micro-SaaS",
    category: "Business",
    tagline: "B2B tools, APIs, niche subscriptions with MRR",
    exampleAttributes: "MRR, churn, customer count, revenue concentration, stack",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Product name", type: "text", required: true },
      { key: "model", label: "Category / ICP", type: "text", required: true, placeholder: "Compliance PDF API for EU accountants" },
      { key: "year", label: "Year launched", type: "number", required: false },
      { key: "condition", label: "Product maturity (1=rough MVP, 10=mature)", type: "number", required: true },
      { key: "purchasePrice", label: "MRR (approx.)", type: "number", required: false, help: "In your local currency per month" },
      { key: "churn", label: "Monthly churn %", type: "number", required: false },
      { key: "techStack", label: "Stack / hosting", type: "text", required: false, placeholder: "Next.js, Postgres, Vercel" },
      {
        key: "payingCustomerCount",
        label: "Paying customers (approx.)",
        type: "number",
        required: false,
      },
      {
        key: "revenueConcentration",
        label: "Top customer share of revenue",
        type: "select",
        required: false,
        options: ["Under 25% from one client", "25 to 50%", "Over 50%", "Unsure"],
      },
    ],
  },

  // ============ Generic / other ============
  {
    id: "general-item",
    name: "Anything Else",
    category: "Other",
    tagline: "Use this for any other item; describe it in detail",
    exampleAttributes: "Category guess, brand, keywords for comps search",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand / maker (if any)", type: "text", required: false },
      { key: "model", label: "What is it?", type: "text", required: true, placeholder: "Vintage Polaroid SX-70 camera" },
      { key: "year", label: "Year", type: "number", required: false },
      purchasePriceField,
      {
        key: "itemCategory",
        label: "What kind of thing is it?",
        type: "select",
        required: false,
        options: ["Tool or machine", "Toy or game", "Home appliance", "Tooling / workshop", "Art or decor", "Something else"],
      },
      {
        key: "keywordsForComps",
        label: "Search keywords a buyer would use",
        type: "text",
        required: false,
        placeholder: "DeWalt 18V hammer drill DCD996",
      },
    ],
  },
];

export function getAssetType(id: string): AssetType | undefined {
  return ASSET_TYPES.find((a) => a.id === id);
}
