import type { AssetType, AssetField } from "@workspace/api-zod";

const sharedExtras = (placeholder: string, help: string): AssetField => ({
  key: "extraNotes",
  label: "Other relevant details",
  type: "textarea",
  required: false,
  placeholder,
  help,
});

const conditionField: AssetField = {
  key: "condition",
  label: "Condition (1=poor, 10=mint)",
  type: "number",
  required: true,
  placeholder: "8",
};

const purchasePriceField: AssetField = {
  key: "purchasePrice",
  label: "Original purchase price",
  type: "number",
  required: false,
  help: "We will assume this is in your local currency.",
};

export const ASSET_TYPES: AssetType[] = [
  // ============ Watches & Jewelry ============
  {
    id: "luxury-watch",
    name: "Luxury Watch",
    category: "Watches & Jewelry",
    tagline: "Rolex, Patek, AP, Omega and other collectible timepieces",
    exampleAttributes: "Reference, box & papers, service history, bracelet",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Rolex" },
      { key: "model", label: "Model / Reference", type: "text", required: true, placeholder: "Submariner 116610LN" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "boxAndPapers", label: "Box & papers?", type: "select", required: false, options: ["Full set (box + papers + tags)", "Watch + box only", "Watch + papers only", "Watch only"] },
      { key: "lastService", label: "Last service year", type: "number", required: false, placeholder: "2024" },
      { key: "ownerCount", label: "Number of previous owners", type: "number", required: false },
      sharedExtras("Original bracelet, no scratches, RSC service Oct 2024", "Service history, bracelet/strap, accessories, defects"),
    ],
  },
  {
    id: "fine-jewelry",
    name: "Fine Jewelry",
    category: "Watches & Jewelry",
    tagline: "Diamonds, rare stones, signed pieces",
    exampleAttributes: "Carat, cut, clarity, certifications",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand / Designer", type: "text", required: false, placeholder: "Cartier" },
      { key: "model", label: "Piece", type: "text", required: true, placeholder: "Love Bracelet, yellow gold" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "metal", label: "Metal", type: "select", required: false, options: ["18k yellow gold", "18k white gold", "18k rose gold", "Platinum", "Silver", "Other"] },
      { key: "stones", label: "Main stones", type: "text", required: false, placeholder: "1.2ct VS1 G center diamond" },
      { key: "certificate", label: "Certificate", type: "select", required: false, options: ["GIA", "IGI", "AGS", "HRD", "None"] },
      sharedExtras("Original box, papers, receipt", "Materials, stones, certifications, hallmarks"),
    ],
  },
  {
    id: "vintage-watch",
    name: "Vintage Watch",
    category: "Watches & Jewelry",
    tagline: "Pre-1990s mechanical watches, military issued, and neo-vintage grails",
    exampleAttributes: "Movement, dial patina, service history",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Omega" },
      { key: "model", label: "Model / Reference", type: "text", required: true, placeholder: "Speedmaster Pre-Moon 145.022" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "movement", label: "Movement", type: "text", required: false, placeholder: "Cal. 861" },
      { key: "boxAndPapers", label: "Box & papers?", type: "select", required: false, options: ["Full set", "Partial", "Watch only"] },
      sharedExtras("Dial & hands original, honest lug holes", "Dial, hands, case polish, service, provenance"),
    ],
  },
  {
    id: "pocket-watch",
    name: "Pocket Watch",
    category: "Watches & Jewelry",
    tagline: "Antique and vintage open-face & hunter-case timepieces",
    exampleAttributes: "Case metal, hallmarks, movement grade",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Maker", type: "text", required: false, placeholder: "Patek Philippe" },
      { key: "model", label: "Description", type: "text", required: true, placeholder: "Gondolo 18k hunter-case minute repeater" },
      { key: "year", label: "Circa year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "caseMaterial", label: "Case material", type: "select", required: false, options: ["Yellow gold", "Rose gold", "White gold", "Silver", "Steel", "Other"] },
      { key: "complications", label: "Complications", type: "text", required: false, placeholder: "Repeater, chronograph" },
      sharedExtras("Running well, crystal clear, chain included", "Movement, case dents, dial hairlines, chain"),
    ],
  },

  // ============ Bags & Fashion ============
  {
    id: "designer-handbag",
    name: "Designer Handbag",
    category: "Bags & Fashion",
    tagline: "Hermès, Chanel, Louis Vuitton and other resale-grade bags",
    exampleAttributes: "Color, leather, hardware, year, receipt",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Hermès" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Birkin 30" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "material", label: "Material / leather", type: "text", required: false, placeholder: "Togo leather" },
      { key: "color", label: "Color", type: "text", required: false, placeholder: "Etoupe" },
      { key: "hardware", label: "Hardware", type: "select", required: false, options: ["Gold", "Silver/Palladium", "Ruthenium", "Other"] },
      { key: "receiptIncluded", label: "Receipt included?", type: "select", required: false, options: ["Yes", "No"] },
      sharedExtras("Dust bag, box, receipt, no corner wear", "Leather, hardware, color, accessories, store"),
    ],
  },
  {
    id: "sneakers",
    name: "Collectible Sneakers",
    category: "Bags & Fashion",
    tagline: "Jordans, Yeezys, Dunks and resale grails",
    exampleAttributes: "Size, deadstock, OG box",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Nike" },
      { key: "model", label: "Model / Colorway", type: "text", required: true, placeholder: "Air Jordan 1 'Chicago Lost & Found'" },
      { key: "year", label: "Release year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "size", label: "Size (US men's)", type: "text", required: true, placeholder: "10" },
      { key: "ogBox", label: "OG box?", type: "select", required: false, options: ["Yes, perfect", "Yes, damaged", "No"] },
      sharedExtras("Deadstock, all OG laces, never worn outside", "Size, OG accessories, creasing, sole condition"),
    ],
  },
  {
    id: "streetwear-apparel",
    name: "Streetwear & Apparel",
    category: "Bags & Fashion",
    tagline: "Supreme, Off-White, vintage band tees, hype drops",
    exampleAttributes: "Size, season, authenticity, flaws",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Supreme" },
      { key: "model", label: "Piece / drop", type: "text", required: true, placeholder: "Box Logo Hoodie FW17" },
      { key: "year", label: "Season / year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "size", label: "Size", type: "text", required: true, placeholder: "M" },
      { key: "authenticity", label: "Proof of authenticity", type: "select", required: false, options: ["Receipt / email order", "StockX / platform auth", "LOA", "No paperwork"] },
      sharedExtras("Worn once, stored flat, no print cracking", "Shrink, fading, stains, reproduction risk"),
    ],
  },
  {
    id: "designer-accessories",
    name: "Designer Accessories",
    category: "Bags & Fashion",
    tagline: "Belts, scarves, small leather goods, sunglasses",
    exampleAttributes: "Brand, hardware, receipt",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Louis Vuitton" },
      { key: "model", label: "Item", type: "text", required: true, placeholder: "Monogram 40mm reversible belt" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "size", label: "Size / dimensions", type: "text", required: false },
      sharedExtras("Original box, dust bag, store receipt", "Wear, hardware tarnish, serial heat stamp"),
    ],
  },

  // ============ Vehicles ============
  {
    id: "classic-car",
    name: "Classic / Collector Car",
    category: "Vehicles",
    tagline: "Vintage, exotic and collectible cars",
    exampleAttributes: "Mileage, matching numbers, restoration history",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Porsche" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "911 Carrera 3.2" },
      { key: "year", label: "Year", type: "number", required: true, placeholder: "1987" },
      conditionField,
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: false, placeholder: "62000" },
      { key: "ownerCount", label: "Number of previous owners", type: "number", required: false, placeholder: "2" },
      { key: "matchingNumbers", label: "Matching numbers / original engine?", type: "select", required: false, options: ["Yes, fully matching", "Engine replaced", "Unsure"] },
      { key: "serviceHistory", label: "Service history", type: "select", required: false, options: ["Full main-dealer", "Full independent specialist", "Partial", "None"] },
      { key: "fuelType", label: "Fuel type", type: "select", required: false, options: ["Petrol", "Diesel", "Hybrid", "Electric"] },
      sharedExtras("No accidents, garage-stored, recent service", "Restoration, accidents, storage, modifications"),
    ],
  },
  {
    id: "everyday-car",
    name: "Everyday Car",
    category: "Vehicles",
    tagline: "Daily-driver cars sold in the local market",
    exampleAttributes: "Mileage, owners, service history, MOT/safety inspection",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Toyota" },
      { key: "model", label: "Model + trim", type: "text", required: true, placeholder: "Corolla Hybrid Excel" },
      { key: "year", label: "Year", type: "number", required: true },
      conditionField,
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: true, placeholder: "48000" },
      { key: "ownerCount", label: "Previous owners", type: "number", required: false, placeholder: "2" },
      { key: "fuelType", label: "Fuel type", type: "select", required: true, options: ["Petrol", "Diesel", "Hybrid", "Plug-in Hybrid", "Electric"] },
      { key: "transmission", label: "Transmission", type: "select", required: false, options: ["Manual", "Automatic", "Other"] },
      { key: "serviceHistory", label: "Service history", type: "select", required: false, options: ["Full main-dealer", "Full independent", "Partial", "None"] },
      { key: "accidents", label: "Accident / damage history", type: "select", required: false, options: ["None", "Minor cosmetic", "Major repaired", "Cat S/N or write-off"] },
      sharedExtras("12 months MOT, full service history, two keys", "Tyres, MOT, keys, modifications"),
    ],
  },
  {
    id: "motorcycle",
    name: "Motorcycle",
    category: "Vehicles",
    tagline: "Modern and classic bikes",
    exampleAttributes: "Mileage, mods, service history",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Ducati" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Panigale V4" },
      { key: "year", label: "Year", type: "number", required: true },
      conditionField,
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: true },
      { key: "ownerCount", label: "Previous owners", type: "number", required: false },
      { key: "mods", label: "Modifications", type: "text", required: false, placeholder: "Akrapovic exhaust, ECU flash" },
      sharedExtras("Garaged, no drops, full service history", "Drops, mods, tyres, service"),
    ],
  },
  {
    id: "boat-marine",
    name: "Boat / Marine",
    category: "Vehicles",
    tagline: "Powerboats, sailboats, RIBs, personal watercraft",
    exampleAttributes: "Length, engine hours, berth, survey",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make / Builder", type: "text", required: true, placeholder: "Sea Ray" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Sundancer 320" },
      { key: "year", label: "Year", type: "number", required: true },
      conditionField,
      purchasePriceField,
      { key: "lengthFt", label: "Length (feet)", type: "number", required: false },
      { key: "engineHours", label: "Engine hours", type: "number", required: false },
      { key: "berth", label: "Home port / mooring", type: "text", required: false, placeholder: "Marina name" },
      sharedExtras("Recent survey, antifouled 2025, trailer included", "Hull, engines, electronics, trailers"),
    ],
  },
  {
    id: "rv-camper",
    name: "RV / Camper",
    category: "Vehicles",
    tagline: "Motorhomes, camper vans, travel trailers",
    exampleAttributes: "Mileage, sleeping capacity, generator",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Make", type: "text", required: true, placeholder: "Winnebago" },
      { key: "model", label: "Model + floorplan", type: "text", required: true, placeholder: "Revel 4x4" },
      { key: "year", label: "Year", type: "number", required: true },
      conditionField,
      purchasePriceField,
      { key: "mileage", label: "Mileage", type: "number", required: false },
      { key: "sleeps", label: "Sleeps (people)", type: "number", required: false },
      { key: "generator", label: "Generator / solar", type: "text", required: false },
      sharedExtras("Full service, two lithium batteries, under warranty", "Water damage, roof seals, appliances"),
    ],
  },

  // ============ Electronics ============
  {
    id: "smartphone",
    name: "Smartphone",
    category: "Electronics",
    tagline: "iPhones, Pixels, Galaxies — current and older models",
    exampleAttributes: "Storage, network lock, battery health",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Apple" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "iPhone 15 Pro Max" },
      { key: "year", label: "Year of purchase", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "storage", label: "Storage", type: "select", required: false, options: ["64GB", "128GB", "256GB", "512GB", "1TB", "2TB"] },
      { key: "color", label: "Color", type: "text", required: false },
      { key: "networkLock", label: "Network status", type: "select", required: false, options: ["Unlocked", "Carrier-locked"] },
      { key: "batteryHealth", label: "Battery health %", type: "number", required: false, placeholder: "92" },
      { key: "boxAndAccessories", label: "Box / accessories", type: "select", required: false, options: ["Original box + cable + all accessories", "Box only", "None"] },
      sharedExtras("AppleCare+ until 2026, no scratches, screen protector since day 1", "Repairs, defects, accessories, warranty"),
    ],
  },
  {
    id: "laptop",
    name: "Laptop / Computer",
    category: "Electronics",
    tagline: "MacBooks, gaming laptops, desktops",
    exampleAttributes: "CPU, RAM, storage, GPU",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Apple" },
      { key: "model", label: "Model + spec", type: "text", required: true, placeholder: "MacBook Pro 14 M3 Pro 18GB/512GB" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "cpu", label: "CPU", type: "text", required: false },
      { key: "ram", label: "RAM (GB)", type: "number", required: false },
      { key: "storage", label: "Storage (GB)", type: "number", required: false },
      { key: "gpu", label: "GPU (if applicable)", type: "text", required: false },
      { key: "batteryHealth", label: "Battery cycles / health", type: "text", required: false },
      sharedExtras("AppleCare to 2026, original box, no dents", "Defects, repairs, accessories, warranty"),
    ],
  },
  {
    id: "gaming-console",
    name: "Gaming Console",
    category: "Electronics",
    tagline: "PS5, Xbox, Switch and retro consoles",
    exampleAttributes: "Storage, controllers, games included",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Sony" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "PlayStation 5 Slim" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "storage", label: "Storage", type: "text", required: false, placeholder: "1TB" },
      { key: "controllers", label: "Controllers included", type: "number", required: false },
      { key: "boxAndAccessories", label: "Box / accessories", type: "select", required: false, options: ["Original box + all cables", "Cables only", "Bare console"] },
      sharedExtras("Boxed, two controllers, includes 5 games", "Bundled games, defects, repairs, region"),
    ],
  },
  {
    id: "camera",
    name: "Camera & Lenses",
    category: "Electronics",
    tagline: "Mirrorless, DSLR, film cameras and pro glass",
    exampleAttributes: "Shutter count, mount, glass condition",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Sony" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "A7 IV body" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "shutterCount", label: "Shutter actuations", type: "number", required: false },
      { key: "lenses", label: "Lenses included", type: "text", required: false, placeholder: "24-70 f/2.8 GM, 70-200 f/4 G" },
      sharedExtras("Original box, two batteries, no scratches on sensor", "Glass condition, repairs, accessories"),
    ],
  },
  {
    id: "tablet",
    name: "Tablet",
    category: "Electronics",
    tagline: "iPad, Galaxy Tab, Surface, e-readers",
    exampleAttributes: "Storage, cellular, accessories, screen",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Apple" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "iPad Pro 12.9 M2" },
      { key: "year", label: "Year of purchase", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "storage", label: "Storage", type: "text", required: false, placeholder: "256GB" },
      { key: "cellular", label: "Cellular?", type: "select", required: false, options: ["WiFi only", "WiFi + Cellular", "N/A"] },
      { key: "boxAndAccessories", label: "Box / accessories", type: "select", required: false, options: ["Original box + charger + pen/keyboard", "Charger only", "Device only"] },
      sharedExtras("Apple Pencil + Magic Keyboard, AppleCare", "Screen wear, battery, keyboard, repairs"),
    ],
  },
  {
    id: "audio-hifi",
    name: "Hi-Fi / Audio",
    category: "Electronics",
    tagline: "Headphones, speakers, amplifiers, DACs, turntables",
    exampleAttributes: "Model, finish, tubes or solid state",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Focal" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Utopia 2022" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "finish", label: "Finish / color", type: "text", required: false },
      { key: "originalBox", label: "Original packaging?", type: "select", required: false, options: ["Full retail box", "Partial", "None"] },
      sharedExtras("Low hours on tubes, balanced cable included", "Drivers, grills, channel imbalance, repairs"),
    ],
  },
  {
    id: "drone-uav",
    name: "Drone / UAV",
    category: "Electronics",
    tagline: "Camera drones, FPV, enterprise UAVs",
    exampleAttributes: "Flight hours, registration, batteries",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "DJI" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Mavic 3 Pro" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "flightHours", label: "Approx. flight hours", type: "number", required: false },
      { key: "batteries", label: "Batteries included", type: "number", required: false },
      { key: "registration", label: "FAA / local registration status", type: "text", required: false },
      sharedExtras("Fly More kit, three batteries, ND filters", "Crashes, gimbal, firmware, controller"),
    ],
  },

  // ============ Real Estate ============
  {
    id: "residential-property",
    name: "Residential Property",
    category: "Real Estate",
    tagline: "Houses, flats, condos — owned or being sold",
    exampleAttributes: "Bedrooms, square footage, year built, location",
    internationallyTradeable: false,
    fields: [
      { key: "model", label: "Property type", type: "select", required: true, options: ["Detached house", "Semi-detached", "Terraced", "Apartment / Flat", "Condo", "Townhouse", "Bungalow"] },
      { key: "brand", label: "Neighbourhood / area", type: "text", required: true, placeholder: "Hampstead, London NW3" },
      { key: "year", label: "Year built", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "bedrooms", label: "Bedrooms", type: "number", required: true },
      { key: "bathrooms", label: "Bathrooms", type: "number", required: false },
      { key: "sqft", label: "Internal area (sq ft)", type: "number", required: false },
      { key: "outdoorSpace", label: "Outdoor space", type: "select", required: false, options: ["Garden", "Balcony", "Terrace", "None"] },
      { key: "tenure", label: "Tenure", type: "select", required: false, options: ["Freehold", "Leasehold", "Share of freehold", "N/A"] },
      sharedExtras("Recent kitchen refurb, EPC C, no chain", "Renovations, EPC, schools, transport, planning permissions"),
    ],
  },
  {
    id: "commercial-property",
    name: "Commercial Property",
    category: "Real Estate",
    tagline: "Retail units, offices, warehouses, mixed-use",
    exampleAttributes: "Sq ft, tenant, yield, lease terms",
    internationallyTradeable: false,
    fields: [
      { key: "model", label: "Property type", type: "select", required: true, options: ["Retail high street", "Shopping unit", "Office", "Industrial / warehouse", "Mixed-use", "Other"] },
      { key: "brand", label: "Location / city", type: "text", required: true, placeholder: "Manchester city centre" },
      { key: "year", label: "Year built", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "sqft", label: "Internal / lettable area (sq ft)", type: "number", required: false },
      { key: "tenure", label: "Tenure", type: "select", required: false, options: ["Freehold", "Long leasehold", "Short leasehold"] },
      { key: "tenant", label: "Tenant / vacancy", type: "text", required: false, placeholder: "Vacant / 5 yr NNN lease to chain" },
      sharedExtras("7% net yield, rent reviewed 2024", "Leases, service charges, planning use class"),
    ],
  },
  {
    id: "land-plot",
    name: "Land / Plot",
    category: "Real Estate",
    tagline: "Building plots, agricultural land, woodland",
    exampleAttributes: "Acreage, planning permission, access",
    internationallyTradeable: false,
    fields: [
      { key: "model", label: "Land type", type: "select", required: true, options: ["Building plot", "Agricultural", "Woodland", "Pasture", "Brownfield", "Other"] },
      { key: "brand", label: "Location", type: "text", required: true, placeholder: "Near Bath, SN13" },
      { key: "acreage", label: "Size (acres)", type: "number", required: false, help: "Use decimals for partial acres" },
      conditionField,
      purchasePriceField,
      { key: "planning", label: "Planning status", type: "text", required: false, placeholder: "Outline PP for 4-bed dwelling" },
      sharedExtras("Full vehicular access, no covenants", "Rights of way, ecology, utilities"),
    ],
  },

  // ============ Collectibles & Art ============
  {
    id: "fine-art",
    name: "Fine Art",
    category: "Collectibles & Art",
    tagline: "Paintings, prints, sculpture",
    exampleAttributes: "Artist, medium, edition, provenance",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Artist", type: "text", required: true, placeholder: "KAWS" },
      { key: "model", label: "Title / Edition", type: "text", required: true, placeholder: "Companion (Open Edition)" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "medium", label: "Medium", type: "text", required: false, placeholder: "Screen print on Saunders paper" },
      { key: "edition", label: "Edition number / size", type: "text", required: false, placeholder: "23 / 100" },
      { key: "provenance", label: "Provenance", type: "text", required: false, placeholder: "Gagosian Gallery, COA included" },
      sharedExtras("Signed, COA included, framed UV glass", "Provenance, signatures, framing, exhibition history"),
    ],
  },
  {
    id: "trading-cards",
    name: "Trading Cards",
    category: "Collectibles & Art",
    tagline: "Sports cards, Pokémon, Magic, etc.",
    exampleAttributes: "Grade, year, set, serial number",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Set / Game", type: "text", required: true, placeholder: "Pokémon Base Set" },
      { key: "model", label: "Card", type: "text", required: true, placeholder: "Charizard Holo 1st Edition" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "grade", label: "Grade & grader", type: "text", required: false, placeholder: "PSA 9" },
      { key: "edition", label: "Edition / set marker", type: "text", required: false, placeholder: "Shadowless 1st edition" },
      sharedExtras("Slabbed, never resubmitted, serial #...", "Grade, grader, set, serial number"),
    ],
  },
  {
    id: "wine-spirits",
    name: "Wine & Spirits",
    category: "Collectibles & Art",
    tagline: "Investment-grade wine, whisky, rare bottles",
    exampleAttributes: "Vintage, fill level, storage, provenance",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Producer", type: "text", required: true, placeholder: "Macallan" },
      { key: "model", label: "Bottling", type: "text", required: true, placeholder: "25 Year Sherry Oak" },
      { key: "year", label: "Vintage / Release year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "bottleSize", label: "Bottle size", type: "select", required: false, options: ["375ml", "500ml", "700ml / 750ml", "1L", "1.5L Magnum", "3L Jeroboam", "Other"] },
      { key: "fillLevel", label: "Fill level", type: "select", required: false, options: ["Into neck / pristine", "High shoulder", "Mid shoulder", "Low shoulder", "Below"] },
      { key: "storage", label: "How was it stored?", type: "select", required: false, options: ["Professional bonded warehouse", "Climate-controlled cellar", "Domestic wine fridge", "Cool dark cupboard", "Room temperature shelf"] },
      { key: "sealed", label: "Seal intact / unopened?", type: "select", required: false, options: ["Yes, sealed", "Capsule slightly worn", "Opened"] },
      { key: "originalBox", label: "Original box / tube?", type: "select", required: false, options: ["Yes, mint", "Yes, worn", "No"] },
      sharedExtras("Bonded since release, original receipts", "Provenance, fills, packaging, storage, label condition"),
    ],
  },
  {
    id: "vinyl-records",
    name: "Vinyl Records",
    category: "Collectibles & Art",
    tagline: "First pressings, rare LPs, signed copies",
    exampleAttributes: "Pressing, matrix, sleeve & vinyl grade",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Artist", type: "text", required: true, placeholder: "The Beatles" },
      { key: "model", label: "Album / pressing", type: "text", required: true, placeholder: "Please Please Me — Stereo Gold/Black 1963 UK 1st" },
      { key: "year", label: "Pressing year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "vinylGrade", label: "Vinyl grade", type: "select", required: false, options: ["Mint (M)", "Near Mint (NM)", "Very Good Plus (VG+)", "Very Good (VG)", "Good (G)", "Fair (F)"] },
      { key: "sleeveGrade", label: "Sleeve grade", type: "select", required: false, options: ["Mint (M)", "Near Mint (NM)", "Very Good Plus (VG+)", "Very Good (VG)", "Good (G)", "Fair (F)"] },
      { key: "matrix", label: "Matrix / runout details", type: "text", required: false },
      sharedExtras("Original inner, no ring wear, plays NM", "Pressing, matrix, signatures, defects"),
    ],
  },
  {
    id: "rare-books",
    name: "Rare Books",
    category: "Collectibles & Art",
    tagline: "First editions, signed copies, antiquarian",
    exampleAttributes: "Edition, dust jacket, signatures",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Author", type: "text", required: true, placeholder: "J.K. Rowling" },
      { key: "model", label: "Title + edition", type: "text", required: true, placeholder: "Harry Potter and the Philosopher's Stone (1st UK 1st print)" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "dustJacket", label: "Dust jacket", type: "select", required: false, options: ["Original, fine", "Original, worn", "Price-clipped", "Missing"] },
      { key: "signed", label: "Signed?", type: "select", required: false, options: ["Yes, in person with COA", "Yes, claimed", "No"] },
      sharedExtras("True first with print line 10 → 1, no foxing", "Edition points, foxing, restoration"),
    ],
  },
  {
    id: "musical-instrument",
    name: "Musical Instrument",
    category: "Collectibles & Art",
    tagline: "Guitars, pianos, vintage synths",
    exampleAttributes: "Maker, year, originality, case",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Maker", type: "text", required: true, placeholder: "Fender" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "American Vintage II '63 Tele" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "originality", label: "Originality", type: "select", required: false, options: ["All original", "Minor period-correct mods", "Modified"] },
      { key: "caseIncluded", label: "Case included?", type: "select", required: false, options: ["Original hard case", "Aftermarket case", "Soft case", "None"] },
      sharedExtras("Plays beautifully, no fret wear, COA from luthier", "Repairs, refrets, refinishes, originality"),
    ],
  },

  // ============ Furniture & Antiques ============
  {
    id: "designer-furniture",
    name: "Designer Furniture",
    category: "Home & Antiques",
    tagline: "Eames, Knoll, Vitra, mid-century classics",
    exampleAttributes: "Maker, year, originality, restoration",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Maker / Designer", type: "text", required: true, placeholder: "Herman Miller / Charles Eames" },
      { key: "model", label: "Piece", type: "text", required: true, placeholder: "Lounge Chair & Ottoman, rosewood" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "originality", label: "Originality", type: "select", required: false, options: ["All original", "Reupholstered (period-correct)", "Restored"] },
      sharedExtras("All original shock mounts, COA from dealer", "Restorations, defects, provenance"),
    ],
  },
  {
    id: "antique",
    name: "Antique / Heirloom",
    category: "Home & Antiques",
    tagline: "100+ year-old pieces, family heirlooms",
    exampleAttributes: "Period, maker, provenance, restoration",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Maker / Workshop", type: "text", required: false },
      { key: "model", label: "Piece", type: "text", required: true, placeholder: "Georgian mahogany sideboard" },
      { key: "year", label: "Approx. year / period", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "provenance", label: "Provenance", type: "text", required: false },
      sharedExtras("In family since 1920, original brasses, no woodworm", "Restorations, period authenticity, marks"),
    ],
  },
  {
    id: "premium-rug",
    name: "Rug / Textile Art",
    category: "Home & Antiques",
    tagline: "Persian, Oriental, designer rugs, tapestries",
    exampleAttributes: "Knot density, size, age, condition",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Origin / workshop", type: "text", required: false, placeholder: "Tabriz" },
      { key: "model", label: "Style / pattern", type: "text", required: true, placeholder: "9x12 medallion, wool & silk" },
      { key: "year", label: "Approx. age (years)", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "dimensions", label: "Dimensions (feet W x L)", type: "text", required: false, placeholder: "8.5 x 11.2" },
      { key: "material", label: "Materials", type: "text", required: false, placeholder: "Hand-knotted wool" },
      sharedExtras("Clean, no moth, paid professional cleaning 2025", "Wear, repairs, dye bleeding, fringes"),
    ],
  },

  // ============ Collectibles (memorabilia) ============
  {
    id: "sports-memorabilia",
    name: "Sports Memorabilia",
    category: "Collectibles & Art",
    tagline: "Signed shirts, match-worn kit, equipment",
    exampleAttributes: "Athlete, authentication, condition, provenance",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Sport / League", type: "text", required: true, placeholder: "NBA" },
      { key: "model", label: "Item + athlete", type: "text", required: true, placeholder: "Michael Jordan signed 1996 Bulls jersey" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "authentication", label: "Authentication", type: "select", required: false, options: ["JSA", "PSA/DNA", "Beckett", "Upper Deck", "Other COA", "None"] },
      { key: "matchWorn", label: "Match-worn / used?", type: "select", required: false, options: ["Match-worn (with photo match)", "Match-worn (claimed)", "Signed only / not used"] },
      sharedExtras("Photo-matched to Game 6 of '96 Finals", "Authentication, provenance, signatures, condition"),
    ],
  },
  {
    id: "comic-books",
    name: "Comic Books",
    category: "Collectibles & Art",
    tagline: "Golden Age to modern keys, manga, graphic novels",
    exampleAttributes: "Issue, variant, grade, pressing",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Publisher / imprint", type: "text", required: true, placeholder: "Marvel" },
      { key: "model", label: "Title & issue", type: "text", required: true, placeholder: "Amazing Fantasy #15" },
      { key: "year", label: "Cover year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "grade", label: "Grade & grader", type: "text", required: false, placeholder: "CGC 4.0" },
      { key: "variant", label: "Variant cover / printing", type: "text", required: false },
      sharedExtras("Newsstand, verified signature Stan Lee", "Restoration, staple rust, ticks, pressing"),
    ],
  },
  {
    id: "numismatics",
    name: "Coins & Currency",
    category: "Collectibles & Art",
    tagline: "Gold & silver bullion, graded coins, banknotes",
    exampleAttributes: "Mint, grade, population",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Country / mint", type: "text", required: true, placeholder: "Royal Mint" },
      { key: "model", label: "Denomination & year", type: "text", required: true, placeholder: "1933 Double Eagle (copy)" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "grade", label: "Grade & service", type: "text", required: false, placeholder: "MS-65 PCGS" },
      { key: "metal", label: "Metal / purity", type: "text", required: false, placeholder: ".999 silver 1 oz" },
      sharedExtras("OG slab, low pop for grade", "Cleaning, scratches, counterfeit risk"),
    ],
  },
  {
    id: "philately",
    name: "Stamps",
    category: "Collectibles & Art",
    tagline: "Classic issues, sheets, postal history",
    exampleAttributes: "Catalogue, condition, provenance",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Country", type: "text", required: true, placeholder: "Great Britain" },
      { key: "model", label: "Issue / catalogue ref", type: "text", required: true, placeholder: "Penny Black (used, 4 margin)" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "catalogue", label: "Catalogue value note", type: "text", required: false, placeholder: "SG catalog £X mint" },
      { key: "certification", label: "Expert certificate?", type: "select", required: false, options: ["Yes", "No", "Pending"] },
      sharedExtras("Mint never hinged, marginal imprint", "Hinges, thins, faults, expertised"),
    ],
  },

  // ============ Sports & Outdoors ============
  {
    id: "bicycle",
    name: "Bicycle",
    category: "Sports & Outdoors",
    tagline: "Road, gravel, mountain, e-bikes",
    exampleAttributes: "Frame, groupset, mileage, size",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Specialized" },
      { key: "model", label: "Model + size", type: "text", required: true, placeholder: "S-Works Tarmac SL8, 56cm" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "groupset", label: "Groupset", type: "text", required: false, placeholder: "Shimano Dura-Ace Di2" },
      { key: "mileage", label: "Approx. mileage (km)", type: "number", required: false },
      { key: "ownerCount", label: "Previous owners", type: "number", required: false },
      sharedExtras("New chain, no crashes, indoor stored", "Crashes, service, upgrades, defects"),
    ],
  },
  {
    id: "golf-equipment",
    name: "Golf Clubs & Gear",
    category: "Sports & Outdoors",
    tagline: "Drivers, irons, putters, bags, launch monitors",
    exampleAttributes: "Shaft, loft, shaft flex",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Titleist" },
      { key: "model", label: "Set / club", type: "text", required: true, placeholder: "TSR3 driver 9°, HZRDUS shaft" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "shaftFlex", label: "Shaft flex", type: "text", required: false, placeholder: "Stiff" },
      { key: "setMakeup", label: "What's included", type: "text", required: false, placeholder: "4-PW + gap wedge, cart bag" },
      sharedExtras("Grip refresh 2025, adjusted lie angles", "Shaft damage, face wear, customization"),
    ],
  },
  {
    id: "winter-sports",
    name: "Winter Sports Gear",
    category: "Sports & Outdoors",
    tagline: "Skis, snowboards, boots, bindings",
    exampleAttributes: "Length, DIN range, boot mondo",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Atomic" },
      { key: "model", label: "Model + size", type: "text", required: true, placeholder: "Bent Chetler 100, 180cm" },
      { key: "year", label: "Season / year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "bindings", label: "Bindings", type: "text", required: false, placeholder: "Shift 13 MN" },
      sharedExtras("One season, tuned edges, no core shots", "Mounts, bases, delamination"),
    ],
  },
  {
    id: "camping-outdoor",
    name: "Camping & Hiking",
    category: "Sports & Outdoors",
    tagline: "Tents, backpacks, sleeping systems, cookware",
    exampleAttributes: "Capacity, weight, season rating",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Hilleberg" },
      { key: "model", label: "Item", type: "text", required: true, placeholder: "Keron 4 GT tent" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "weight", label: "Weight (kg)", type: "number", required: false },
      sharedExtras("Used three weekends, seam-sealed, all pegs", "UV fade, zipper wear, stains"),
    ],
  },
  {
    id: "fitness-equipment",
    name: "Home Fitness Equipment",
    category: "Sports & Outdoors",
    tagline: "Bikes, rowers, racks, adjustable dumbbells",
    exampleAttributes: "Usage hours, screen, subscription",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Brand", type: "text", required: true, placeholder: "Peloton" },
      { key: "model", label: "Model", type: "text", required: true, placeholder: "Bike+ with rotating screen" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      { key: "usage", label: "Approx. rides / hours", type: "text", required: false, placeholder: "450 rides" },
      { key: "subscription", label: "Subscription transferable?", type: "select", required: false, options: ["Yes", "No", "N/A"] },
      sharedExtras("Original mat & shoes, membership through Q2", "Noise, calibration, recalls, scratches"),
    ],
  },
  {
    id: "saas-micro",
    name: "SaaS / Micro-SaaS",
    category: "Business",
    tagline: "B2B tools, APIs, niche subscriptions with MRR",
    exampleAttributes: "MRR, churn, stack, code ownership",
    internationallyTradeable: false,
    fields: [
      { key: "brand", label: "Product name", type: "text", required: true },
      { key: "model", label: "Category / ICP", type: "text", required: true, placeholder: "Compliance PDF API for EU accountants" },
      { key: "year", label: "Year launched", type: "number", required: false },
      { key: "condition", label: "Product maturity (1=rough MVP, 10=mature)", type: "number", required: true },
      { key: "purchasePrice", label: "MRR (approx.)", type: "number", required: false, help: "In your local currency per month" },
      { key: "churn", label: "Monthly churn %", type: "number", required: false },
      { key: "techStack", label: "Stack / hosting", type: "text", required: false, placeholder: "Next.js, Postgres, Vercel" },
      sharedExtras("100% owned code, documented handover, Stripe Connect", "Tech debt, compliance, key-person risk, dependencies"),
    ],
  },

  // ============ Generic / other ============
  {
    id: "general-item",
    name: "Anything Else",
    category: "Other",
    tagline: "Use this for any other item; describe it in detail",
    exampleAttributes: "Anything that helps a buyer understand what it is and why it has value",
    internationallyTradeable: true,
    fields: [
      { key: "brand", label: "Brand / maker (if any)", type: "text", required: false },
      { key: "model", label: "What is it?", type: "text", required: true, placeholder: "Vintage Polaroid SX-70 camera" },
      { key: "year", label: "Year", type: "number", required: false },
      conditionField,
      purchasePriceField,
      sharedExtras("Tell us everything — materials, history, why it's special", "Materials, history, accessories, why it's worth what you think"),
    ],
  },
];

export function getAssetType(id: string): AssetType | undefined {
  return ASSET_TYPES.find((a) => a.id === id);
}
